; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

	TITLE	C:\cpython\externals\zlib-1.2.11\contrib\vstudio\vc14\x86\TestZlibDebug\Tmp\inffast.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
